product_samples = [
    "Tôi muốn mở thẻ tín dụng.",
    "Tôi cần thông tin về lãi suất.",
    "Có phí thường niên không?",
    "Tôi có thể quản lý thẻ tín dụng qua ứng dụng không?",
    "Thời gian duyệt hồ sơ là bao lâu?",
    "Tôi muốn biết cách thanh toán hóa đơn.",
    "Có chương trình khuyến mãi nào không?",
    "Tôi muốn tăng hạn mức tín dụng.",
    "Có thể chuyển đổi điểm thưởng thành tiền mặt không?",
    "Tôi muốn báo mất thẻ tín dụng.",
    "Tôi cần hỗ trợ kỹ thuật cho ứng dụng ngân hàng.",
    "Tôi muốn biết cách bảo mật thông tin tài khoản.",
    "Tôi muốn đăng ký thẻ tín dụng mới.",
    "Tôi cần thông tin về các loại thẻ tín dụng.",
    "Tôi muốn biết cách sử dụng thẻ tín dụng nước ngoài.",
    "Tôi muốn biết cách hủy thẻ tín dụng.",
    "Tôi muốn biết cách sử dụng thẻ tín dụng quốc tế.",
    "Tôi muốn biết cách sử dụng thẻ tín dụng trả góp.",
    "Tôi muốn biết cách sử dụng thẻ tín dụng cho mua sắm trực tuyến.",
    "Tôi muốn biết cách sử dụng thẻ tín dụng cho du lịch."
]

chitchat_samples = [
    "Xin chào! Tôi có thể giúp gì cho bạn hôm nay?",
    "Thời tiết hôm nay thế nào?",
    "Kể cho tôi một câu chuyện cười.",
    "Bạn có biết tin tức mới nhất không?",
    "Tôi muốn nghe một bài hát hay.",
    "Bạn có sở thích gì không?",
    "Bạn có thể giới thiệu một cuốn sách hay không?",
    "Tôi muốn biết về các bộ phim mới ra mắt.",
    "Bạn có biết cách nấu món ăn nào ngon không?",
    "Tôi muốn biết về các sự kiện sắp tới.",
    "Bạn có thể giúp tôi tìm một nhà hàng tốt không?",
    "Tôi muốn biết về các hoạt động giải trí trong thành phố.",
    "Bạn có thể gợi ý một chuyến du lịch thú vị không?",
    "Tôi muốn biết về các hoạt động thể thao đang diễn ra.",
    "Bạn có thể giúp tôi tìm một công việc không?",
    "Tôi muốn biết về các khóa học trực tuyến.",
    "Bạn có thể giúp tôi tìm hiểu về công nghệ mới không?",
    "Tôi muốn biết về các xu hướng thời trang hiện nay.",
    "Bạn có thể giúp tôi tìm hiểu về sức khỏe và dinh dưỡng không?",
    "Tôi muốn biết về các mẹo làm đẹp."
]
