services:

  mychatbot:
    build:
      context: ..
      dockerfile: cicd/Dockerfile
    container_name: chatbot_system_container
    working_dir: /app/core
    volumes:
      - ../core:/app/core
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8000:8000"
    restart: always

  streamlit_fe:
    build:
      context: ..
      dockerfile: fe-streamlit/Dockerfile
    container_name: streamlit_fe_container
    working_dir: /app
    volumes:
      - ../fe-streamlit:/app
    ports:
      - "8501:8501"
    restart: always